name: Minecraft PE Server

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Chạy lại hàng ngày để đảm bảo server luôn mới

jobs:
  minecraft-server:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d
        
    - name: Expose server with ngrok
      uses: https://github.com/marketplace/actions/ngrok-tunnel-action
      with:
        ngrok-version: 'latest'
        auth-token: ${{ secrets.NGROK_AUTH_TOKEN }}
        proto: udp
        addr: 19132
        region: ap # Chọn region gần bạn (us, eu, ap, au, sa, jp, in)
        
    - name: Get ngrok URL
      id: ngrok
      run: |
        sleep 5 # Đợi ngrok khởi tạo
        NGROK_URL=$(curl -s localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
        echo "Ngrok URL: $NGROK_URL"
        echo "ngrok_url=$NGROK_URL" >> $GITHUB_OUTPUT
        
    - name: Save ngrok URL
      run: |
        echo "${{ steps.ngrok.outputs.ngrok_url }}" > ngrok_url.txt
        
    - name: Upload ngrok URL
      uses: actions/upload-artifact@v2
      with:
        name: ngrok-url
        path: ngrok_url.txt
        
    - name: Keep server running
      run: |
        while true; do
          sleep 300
          echo "Server is still running..."
        done
